# Server configuration
# prettier-ignore
server:
    ip: "127.0.0.1"                    # IP to which the plugin will send the data (developer only)
    port: 6000                         # Port to which the plugin will send the data (developer only)

# prettier-ignore
frequency: 60                          # Frequency of the data sent to the server, in Hz


# The user can choose which signals will be sent to the server, in case of bad performance, the user can disable some data
# Signal activation
# prettier-ignore
signals:
    clutchRPM: 1                       # Clutch RPM
    deltaTime: 1                       # Time between frames
    engineOilTemp: 1                   # Engine oil temperature
    engineWaterTemp: 1                 # Engine water temperature
    lapNumber: 1                       # Lap number
    lapStartET: 1                      # Lap start elapsed time
    lapDistance: 1                     # Lap distance
    bestS1: 1                          # Best sector 1 time
    bestS2: 1                          # Best sector 2 time (plus sector 1)
    bestLap: 1                         # Best laptime
    lastS1: 1                          # Last sector 1 time
    lastS2: 1                          # Last sector 2 time (plus sector 1)
    lastLap: 1                         # Last laptime
    currentS1: 1                       # Current sector 1 time
    currentS2: 1                       # Current sector 2 time (plus sector 1)
    numPitstops: 1                     # Number of pitstops
    numPenalties: 1                    # Number of penalties
    localAccelX: 1                     # Local X acceleration
    localAccelY: 1                     # Local Y acceleration
    localAccelZ: 1                     # Local Z acceleration
    localRotX: 1                       # Local X rotation
    localRotY: 1                       # Local Y rotation
    localRotZ: 1                       # Local Z rotation
    localRotAccelX: 1                  # Local X rotation acceleration
    localRotAccelY: 1                  # Local Y rotation acceleration
    localRotAccelZ: 1                  # Local Z rotation acceleration
    localVelX: 1                       # Local X velocity
    localVelY: 1                       # Local Y velocity
    localVelZ: 1                       # Local Z velocity
    oriXX: 1                           # Orientation XX
    oriXY: 1                           # Orientation XY
    oriXZ: 1                           # Orientation XZ
    oriYX: 1                           # Orientation YX
    oriYY: 1                           # Orientation YY
    oriYZ: 1                           # Orientation YZ
    oriZX: 1                           # Orientation ZX
    oriZY: 1                           # Orientation ZY
    oriZZ: 1                           # Orientation ZZ
    posX: 1                            # Position X
    posY: 1                            # Position Y
    posZ: 1                            # Position Z
    steeringArmForce: 1                # Steering arm force
    trackName: 1                       # Track name
    driverName: 1                      # Driver name
    vehicleName: 1                     # Vehicle name
    speed: 1                           # Speed
    accelLat: 1                        # Lateral acceleration
    accelLong: 1                       # Longitudinal acceleration
    roll: 1                            # Roll
    pitch: 1                           # Pitch
    rpm: 1                             # RPM
    maxRPM: 1                          # Max RPM
    lapIniTime: 1                      # Lap initial time
    brake: 1                           # Brake
    clutch: 1                          # Clutch
    steering: 1                        # Steering
    throttle: 1                        # Throttle
    gear: 1                            # Gear
    brakeTempFL: 1                     # Brake temperature Front Left
    brakeTempFR: 1                     # Brake temperature Front Right
    brakeTempRL: 1                     # Brake temperature Rear Left
    brakeTempRR: 1                     # Brake temperature Rear Right
    gripFactorFL: 1                    # Grip factor Front Left
    gripFactorFR: 1                    # Grip factor Front Right
    gripFactorRL: 1                    # Grip factor Rear Left
    gripFactorRR: 1                    # Grip factor Rear Right
    lateralForceFL: 1                  # Lateral force Front Left
    lateralForceFR: 1                  # Lateral force Front Right
    lateralForceRL: 1                  # Lateral force Rear Left
    lateralForceRR: 1                  # Lateral force Rear Right
    pressureFL: 1                      # Pressure Front Left
    pressureFR: 1                      # Pressure Front Right
    pressureRL: 1                      # Pressure Rear Left
    pressureRR: 1                      # Pressure Rear Right
    rideHeightFL: 1                    # Ride height Front Left
    rideHeightFR: 1                    # Ride height Front Right
    rideHeightRL: 1                    # Ride height Rear Left
    rideHeightRR: 1                    # Ride height Rear Right
    rotationFL: 1                      # Rotation Front Left
    rotationFR: 1                      # Rotation Front Right
    rotationRL: 1                      # Rotation Rear Left
    rotationRR: 1                      # Rotation Rear Right
    shockDeflectionFL: 1               # Shock deflection Front Left
    shockDeflectionFR: 1               # Shock deflection Front Right
    shockDeflectionRL: 1               # Shock deflection Rear Left
    shockDeflectionRR: 1               # Shock deflection Rear Right
    tireTempFLI: 1                     # Tire temperature Front Left Inner
    tireTempFLM: 1                     # Tire temperature Front Left Middle
    tireTempFLO: 1                     # Tire temperature Front Left Outer
    tireTempFRI: 1                     # Tire temperature Front Right Inner
    tireTempFRM: 1                     # Tire temperature Front Right Middle
    tireTempFRO: 1                     # Tire temperature Front Right Outer
    tireTempRLI: 1                     # Tire temperature Rear Left Inner
    tireTempRLM: 1                     # Tire temperature Rear Left Middle
    tireTempRLO: 1                     # Tire temperature Rear Left Outer
    tireTempRRI: 1                     # Tire temperature Rear Right Inner
    tireTempRRM: 1                     # Tire temperature Rear Right Middle
    tireTempRRO: 1                     # Tire temperature Rear Right Outer
    tireLoadFL: 1                      # Tire load Front Left
    tireLoadFR: 1                      # Tire load Front Right
    tireLoadRL: 1                      # Tire load Rear Left
    tireLoadRR: 1                      # Tire load Rear Right
    tireWearFL: 1                      # Tire wear Front Left
    tireWearFR: 1                      # Tire wear Front Right
    tireWearRL: 1                      # Tire wear Rear Left
    tireWearRR: 1                      # Tire wear Rear Right
    detached: 1                        # Whether any part (besides wheels) is detached
    detachedFL: 1                      # Whether the Front Left wheel is detached
    detachedFR: 1                      # Whether the Front Right wheel is detached
    detachedRL: 1                      # Whether the Rear Left wheel is detached
    detachedRR: 1                      # Whether the Rear Right wheel is detached
    overheating: 1                     # Whether the overheating icon is shown in the screen
    flatFL: 1                          # Whether the Front Left tire is flat
    flatFR: 1                          # Whether the Front Right tire is flat
    flatRL: 1                          # Whether the Rear Left tire is flat
    flatRR: 1                          # Whether the Rear Right tire is flat
    surfaceFL: 1                       # Surface type Front Left
    surfaceFR: 1                       # Surface type Front Right
    surfaceRL: 1                       # Surface type Rear Left
    surfaceRR: 1                       # Surface type Rear Right
    lastImpactET: 1                    # Elapsed time of the last impact
    lastImpactMagnitude: 1             # Magnitude of the last impact
    lastImpactPosX: 1                  # Position X of the last impact
    lastImpactPosY: 1                  # Position Y of the last impact
    lastImpactPosZ: 1                  # Position Z of the last impact
    scheduledStops: 1                  # Number of scheduled stops
    fuel: 1                            # Fuel
    isPlayer: 1                        # Whether the player is driving
    whoIsInControl: 1                  # Who is in control of the vehicle (-1=nobody (shouldn't get this), 0=local player, 1=local AI, 2=remote, 3=replay (shouldn't get this))
    isInPit: 1                         # Whether the vehicle is in the pit
    vehicleClass: 1                    # Vehicle class
    deltaTimeBehind: 1                 # Time behind the vehicle in front
    deltaLapsBehind: 1                 # Laps behind the vehicle in front
    deltaTimeLeader: 1                 # Time behind the leader
    deltaLapsLeader: 1                 # Laps behind the leader
    numOfVehicles: 1                   # Current number of vehicles
    terrainName: 1                     # Terrain name from the TDF file
